### ISSUE TITLE
Create Admin Auth for admin portal

### ISSUE THREAD

**Issue by kevinmirc** [ncma-chapters/team#33]
**Should include**
- Sign in, Password Reset, (optionally) Sign up.
- Authentication should provide a JWT token back.

**Options**
- [x] Amplify
Let's not use amplify...
- [x] AWS Cognito use pool without amplify

**Comment by kelsonic** [comment]
Replacing `ncma-chapter-web` label with `ncma-chapter-admin-web` @kevinmirc

**Comment by kevinmirc** [comment]
**Details**
See Client ID and Host URL [here](https://console.aws.amazon.com/cognito/users/?region=us-east-1#/pool/us-east-1_xwpBLxNGM/app-integration-app-settings?_k=0kr30q)
- **Callback URL**: `http://localhost:8080/auth/callback`
- **Signout URL**: `http://localhost:8080/auth/sign-out`

**Comment by kevinmirc** [comment]
@kelsonic Is this closed?

**Comment by kevinmirc** [comment]
Completed
