### ISSUE TITLE
Remove Address and Phone number on website

### ISSUE THREAD

**Issue by kevinmirc** [ncma-chapters/team#34]
# Description

The website owners would like the `address` removed until the chapter has an official one (like a PO box or something). The `phone` should also be removed from the website.

## Acceptance Criteria
- [ ] Remove `address` and `phone` from Footer.
- [ ] Remove `address` and `phone` from Contact page.

**Comment by kelsonic** [comment]
Removed `address` and `phone` from Footer and Contact page. Validated on ncmamonmouth.org. Closing! 🎉
