### ISSUE TITLE
Write the email a website user received after registering for an event

### ISSUE THREAD

**Issue by kevinmirc** [ncma-chapters/team#36]
**Requirements**: Subject Line, Email Body.

**Related Work**
Design: https://github.com/ncma-chapters/team/issues/37
API: https://github.com/ncma-chapters/team/issues/35

**Comment by psanders86** [comment]
# Email Subject Line
Confirmed! You're on the list

# Email Registration Confirmation 
*This email is for a fictional NCMA Luncheon event. Ideally, the name of the event can be autopopulated.*

Dear XXXXXX

Congratulations, you have successfully registered for our **NCMA Luncheon.** We look forward to seeing you! Here are some details about the event:

**NCMA Luncheon**
**Time:** 1:30 p.m. – 2:30 p.m.
**Date:** Thursday, June 4, 2020
**Address:** Jersey Diner, 123 Barnaby Way, Point Pleasant, NJ 04326

NCMA events are great ways for contract managers to turbocharge their careers. This is where you’ll hear some of the latest thought leadership in our field, as well as network with other contract managers from around the region.

Now that you’ve reserved your spot, we would love it if you helped spread the word over social media. Please use the hashtag **#NCMAMonmouth**.

If you have any questions, just reply to this email and someone will respond as soon as possible.

We’ll see you in **JUNE!**

Best regards,

Joshua Cohen
Acting President
NCMA Monmouth Chapter

# Email Event Reminder

**NCMA Monmouth Chapter**
Event Reminder

This is an automatic reminder of the following event:

### NCMA Luncheon

**Time**
Thursday, June 4, 2020, 1:30 p.m. – 2:30 p.m.

**Attendee**
John Doe

**Do you need to cancel?**
Click here to cancel your reservation

Remember to use the hashtag **#NCMAMonmouth** when talking about the event on Facebook and Twitter.

Parking is available at the site. We look forward to seeing you!
